### ISSUE TITLE
Replacement of CDN

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#122]
Currently we are using CDN to load bootstrap for the forum views but we will end up with 2 different versions of BS - one from CDN and the other what user is using. We need a way to include the compiled assets and have them published with vendor:publish, with a configurable assets path. We are looking for the best way to achieve this. (may be post-MVP due to complexity)

**Comment by Riari** [comment]
You do realise that even without using a CDN, the package user might still end up with two Bootstrap versions?

It doesn't matter how we load it. The point of including it is to make the forum views render properly out of the box because we can't assume Bootstrap is loaded by the host application already. If it is, the user is free to remove our CDN link - the package master view would need to be overridden anyway in order to wrap the host app's view around it, so it's hardly an inconvenience for the user.

My suggestion is that we stick to using the CDN link for Bootstrap, but for any custom CSS/JS, we use Mix, commit the compiled, prod-ready assets and have `vendor:publish` throw them into `public/assets/forum.css` and `public/assets/forum.js`. The config option for the assets path should then be `public/assets` by default, which gives the user a few choices:

- Keep the stock CSS and just override it in their own CSS if they wish to
- Change the asset path to a different one where they have their own versions of `forum.css` and `forum.js`
- Remove the CSS and JS links from the package's master view altogether and write 100% custom forum CSS/JS (either from scratch or by copying the source LESS/JS files from the package directory and including them in the application's mix routine)
