### ISSUE TITLE
Interface for User Model

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#159]
Since we don't have control over the User model, creating an interface would be a good idea to handle this. As mentioned in #157 right now it is overkill but it is something worth having in the future. Creating this issue for future reference

**Comment by Riari** [comment]
I think we need to use a trait for this since an interface won't provide the implementation. Could include an interface as well, but as we'd already be asking the package user to add a trait to their user model, there's little point in doing more than that.

**Comment by deleugpn** [comment]
@Riari the interface is for us, not for the users. It's pretty much a practical example of `program to an interface` concept of SOLID. We do not have control over the User and when we want to type-hint objects for auto-wire in the dependency injection, for instance, we cannot do so through a trait.

**Comment by Riari** [comment]
But we only depend on code that comes from the trait, which is our own. It only becomes an issue if the user overrides our trait methods or doesn't include it at all, in which case they cannot expect it to work properly anyway.

Asking them to implement the interface as well is barely any better than simply saying "add this trait and don't fuck with it". It's more hassle for very little gain.

**Comment by deleugpn** [comment]
I don't disagree with you. But again, you're talking about the use of the forum. I'm talking about the development of it. We cannot type-hint `App\User` because it doesn't exist and we cannot type-hint our test stub because that's only for tests. 

https://github.com/bitporch/laravel-forum/pull/174/files#diff-8362343e88c6b6fedd66b2109bd0f54bR13 Here we could type-hint the interface, but this is not a good example because it's a parameter passed manually. But at some point we might want to use dependency injection and that will not work with a trait.

**Comment by Riari** [comment]
We have so little reliance on the user model that I really don't think being able to type hint it is important enough to warrant making users implement an interface.

**Comment by Riari** [comment]
There is an alternative for typehinting/DI purposes:

```
AliasLoader::getInstance()->alias('ForumUser', config('forum.user'));
```

But I'm still not convinced that we need them. We just use what, two relationships and the primary key?

**Comment by Dylan-DPC** [comment]
I agree with Riari here. Right now we are depending only on relations whose code will be the same almost everywhere.

**Comment by AndreasElia** [comment]
Trait it is.
