### ISSUE TITLE
Web & API Duplication

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#170]
Currently as witnessed in #166, we will end up duplicating features for the web and API modules of the package. For every new feature we have to create 2 identical classes that will mostly differ only in the data returned by the function. 

To avoid this, we can do either one of the following:
1) make the web module consume the API
2) create a "repository" layer (or whatever you want to call it) that is used by both modules

thoughts... ?

**Comment by Riari** [comment]
Would advise against the first option, having tried it myself and seen how ugly it is. A repository layer wouldn't really help us here because as you said, the difference is (almost) exclusively in the way responses are given, not how data is retrieved.

So we might just be able to use a single set of controllers and have the appropriate response given based on the request - which could be as simple as a `respond` method in the base controller that handles it.

Either that or we just leave it as is because frankly, the controller actions are already pretty thin so I don't think it's a significant problem.

**Comment by Riari** [comment]
I stand corrected on my second point after some discussion - @deleugpn's example PR (#174) shows that extracting Eloquent calls into service classes is an elegant way around this. Still a big fat "NO" to using the repo pattern 😛 but this is a nice compromise. I think we should just run with it.

**Comment by AndreasElia** [comment]
Running with the service classes.
