### ISSUE TITLE
Don't store the body of discussion as a Post

### ISSUE THREAD

**Issue by deleugpn** [bitporch/laravel-forum#181]
I noticed from the code that when creating a discussion the first `Post` is the Discussion body itself, which requires a structure more or less like this: 

- Create discussion record;
- Create post record;
- Update discussion record to save the first_post_id;

Instead, having a body/content column inside discussion table would allow us to save the body of a discussion separately from a Post/Reply, not to mention that it would make the algorithm itself simpler by not having to go back one entity after creating another.

I say this because A) I have a small support ticket project that I work as a freelancer and I made this same mistake and now it's giving me headaches. I'm changing the structure of the ticket to have a body instead of using the 1st reply to identify the body and B) I'm watching the Lets build a forum from Jeffrey Way and he implements the same suggestion I'm making here.

**Comment by Riari** [comment]
I disagree. This came up on Larachat a week or so ago and the general consensus was to stick with what we have. A post is a post, so treat it like one, otherwise every post interaction (editing, quoting, individual post linking, any post-related feature implemented in the future, etc) has to be handled separately - which is simply not worth it just to save making an additional query (incidentally, I think we're supposed to be dropping `first_post_id` from the discussions table).

**Comment by Dylan-DPC** [comment]
I agree with that. it will add unnecessary complexity to include it for discussions.

**Comment by AndreasElia** [comment]
Going to keep everything which is a post as a post, I see you're coming from but I feel this is cleaner and worth the little bit more work it takes to work with.
