### ISSUE TITLE
View Count

### ISSUE THREAD

**Issue by MadMikeyB** [bitporch/laravel-forum#23]
We were just discussing how best to implement view counts for Discussions on Larachat.

A good implementation (not sure about for a package) would be Redis, as it wouldn't require a DB hit necessarily.

Either that, or a view_count column in the DB table - obviously that would be subject to heavy caching and indexing for performance reasons.

My main worry would be that a view_count column would be hit (almost) every page load which would be yet another DB call.

If we really wanted to go overboard we could set up a pivot table, with an associated trait, so each content type could support view counts. This would have the advantage of hitting a lesser used database table and not a discussions table which may be more heavily used the larger the forum.

**Comment by Dylan-DPC** [comment]
Will be handled during pagination

**Comment by Riari** [comment]
> If we really wanted to go overboard we could set up a pivot table, with an associated trait, so each content type could support view counts.
I don't think this is overboard at all and in fact a very good idea. Think of it like a plugin for the forum - it's definitely worth considering building features like this as separate packages. I ended up doing the same thing when I needed view counting (code [here](https://github.com/Team-Tea-Time/laravel-counter)), just never got around to integrating it.

Any additional packages that can be used to enable such features could also be added to the `suggest` section of the composer manifest: https://getcomposer.org/doc/04-schema.md#suggest

Regarding any caching that might be done, I think it's probably wise to just use Laravel's cache service rather than using Redis or something else directly. That way, the package user can decide exactly what cache driver to use.

**Comment by MadMikeyB** [comment]
>>>Will be handled during pagination
View Counting? I thought that was post counting.
>>>I don't think this is overboard at all and in fact a very good idea.
Thanks. I think you caught my meaning by 'overboard' when you suggested making it a separate package 👍
